package i18n

import (
	"os"
	"strings"
)

// Language represents a supported language
type Language string

const (
	// English is the default language
	English Language = "en"
	// French language support
	French Language = "fr"
)

// CurrentLanguage is the currently active language
var CurrentLanguage Language = English

// MessageKey represents a key for a translatable message
type MessageKey string

// Translation keys for markdown formatting
const (
	// Summary section
	KeySummary    MessageKey = "summary"
	KeyConfidence MessageKey = "confidence"
	KeyEstimation MessageKey = "estimation"

	// Financial Preview section
	KeyFinancialPreview MessageKey = "financial_preview"
	KeyType             MessageKey = "type"
	KeyTime             MessageKey = "time"
	KeyCost             MessageKey = "cost"
	KeyMaximum          MessageKey = "maximum"
	KeyMinimum          MessageKey = "minimum"

	// Cost by Category section
	KeyCostByCategory MessageKey = "cost_by_category"
	KeyCategory       MessageKey = "category"

	// Tasks section
	KeyTasks       MessageKey = "tasks"
	KeyTask        MessageKey = "task"
	KeyOptimistic  MessageKey = "optimistic"
	KeyLikely      MessageKey = "likely"
	KeyPessimistic MessageKey = "pessimistic"
	KeyMean        MessageKey = "mean"
	KeySD          MessageKey = "sd"

	// Category Distribution section
	KeyCategoryDistribution   MessageKey = "category_distribution"
	KeyEstimationDistribution MessageKey = "estimation_distribution"
	KeyPercentage             MessageKey = "percentage"

	// Synthesis section
	KeyEstimationSynthesis MessageKey = "estimation_synthesis"
	KeySources             MessageKey = "sources"
	KeyFile                MessageKey = "file"
	KeyLabel               MessageKey = "label"
	KeySource              MessageKey = "source"

	// Footer
	KeyGeneratedBy MessageKey = "generated_by"

	// Categories section
	KeyCategories      MessageKey = "categories"
	KeyCostPerTimeUnit MessageKey = "cost_per_time_unit"
)

// translations holds all translations for all languages
var translations = map[Language]map[MessageKey]string{
	English: {
		KeySummary:                "Summary",
		KeyConfidence:             "Confidence",
		KeyEstimation:             "Estimation",
		KeyFinancialPreview:       "Financial Preview",
		KeyType:                   "Type",
		KeyTime:                   "Time",
		KeyCost:                   "Cost",
		KeyMaximum:                "Maximum",
		KeyMinimum:                "Minimum",
		KeyCostByCategory:         "Cost by Category",
		KeyCategory:               "Category",
		KeyTasks:                  "Tasks",
		KeyTask:                   "Task",
		KeyOptimistic:             "Optimistic",
		KeyLikely:                 "Likely",
		KeyPessimistic:            "Pessimistic",
		KeyMean:                   "Mean",
		KeySD:                     "SD",
		KeyCategoryDistribution:   "Category Distribution",
		KeyEstimationDistribution: "Estimation Distribution",
		KeyPercentage:             "Percentage",
		KeyEstimationSynthesis:    "Estimation Synthesis",
		KeySources:                "Sources",
		KeyFile:                   "File",
		KeyLabel:                  "Label",
		KeySource:                 "Source",
		KeyGeneratedBy:            "Generated by Guesstimate CLI on %s",
		KeyCategories:             "Categories",
		KeyCostPerTimeUnit:        "Cost per Time Unit",
	},
	French: {
		KeySummary:                "Résumé",
		KeyConfidence:             "Confiance",
		KeyEstimation:             "Estimation",
		KeyFinancialPreview:       "Aperçu financier",
		KeyType:                   "Type",
		KeyTime:                   "Temps",
		KeyCost:                   "Coût",
		KeyMaximum:                "Maximum",
		KeyMinimum:                "Minimum",
		KeyCostByCategory:         "Coût par catégorie",
		KeyCategory:               "Catégorie",
		KeyTasks:                  "Tâches",
		KeyTask:                   "Tâche",
		KeyOptimistic:             "Optimiste",
		KeyLikely:                 "Probable",
		KeyPessimistic:            "Pessimiste",
		KeyMean:                   "Moyenne",
		KeySD:                     "É.T.",
		KeyCategoryDistribution:   "Distribution par catégorie",
		KeyEstimationDistribution: "Répartition par estimation",
		KeyPercentage:             "Pourcentage",
		KeyEstimationSynthesis:    "Synthèse des estimations",
		KeySources:                "Sources",
		KeyFile:                   "Fichier",
		KeyLabel:                  "Libellé",
		KeySource:                 "Source",
		KeyGeneratedBy:            "Généré par Guesstimate CLI le %s",
		KeyCategories:             "Catégories",
		KeyCostPerTimeUnit:        "Coût par unité de temps",
	},
}

// T returns the translation for the given key in the current language
func T(key MessageKey) string {
	if langTrans, ok := translations[CurrentLanguage]; ok {
		if trans, ok := langTrans[key]; ok {
			return trans
		}
	}
	// Fallback to English
	if langTrans, ok := translations[English]; ok {
		if trans, ok := langTrans[key]; ok {
			return trans
		}
	}
	return string(key)
}

// SetLanguage sets the current language
func SetLanguage(lang Language) {
	// Validate the language
	if _, ok := translations[lang]; ok {
		CurrentLanguage = lang
	} else {
		CurrentLanguage = English
	}
}

// SetLanguageFromString sets the current language from a string
func SetLanguageFromString(lang string) {
	switch strings.ToLower(lang) {
	case "en", "english", "eng":
		SetLanguage(English)
	case "fr", "french", "fra", "français":
		SetLanguage(French)
	default:
		SetLanguage(English)
	}
}

// GetLanguageFromEnv detects language from environment variables
func GetLanguageFromEnv() Language {
	// Check LANG environment variable
	lang := os.Getenv("LANG")
	if lang != "" {
		lang = strings.ToLower(lang)
		if strings.HasPrefix(lang, "fr") {
			return French
		}
		if strings.HasPrefix(lang, "en") {
			return English
		}
	}

	// Check LC_ALL
	lcAll := os.Getenv("LC_ALL")
	if lcAll != "" {
		lcAll = strings.ToLower(lcAll)
		if strings.HasPrefix(lcAll, "fr") {
			return French
		}
		if strings.HasPrefix(lcAll, "en") {
			return English
		}
	}

	// Check LANGUAGE
	language := os.Getenv("LANGUAGE")
	if language != "" {
		language = strings.ToLower(language)
		if strings.HasPrefix(language, "fr") {
			return French
		}
		if strings.HasPrefix(language, "en") {
			return English
		}
	}

	return English
}

// InitLanguage initializes the language from config or environment
func InitLanguage(configLang string) {
	if configLang != "" {
		SetLanguageFromString(configLang)
		return
	}

	// Try environment
	envLang := GetLanguageFromEnv()
	if envLang != English {
		SetLanguage(envLang)
	}
}

// GetCurrentLanguage returns the current language
func GetCurrentLanguage() Language {
	return CurrentLanguage
}

// GetSupportedLanguages returns a list of supported languages
func GetSupportedLanguages() []Language {
	var langs []Language
	for lang := range translations {
		langs = append(langs, lang)
	}
	return langs
}
